// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgyfksanxkrcaqlwxkkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneWZrc2FueGtyY2FxbHd4a2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjM1NzksImV4cCI6MjA2MjkzOTU3OX0.WZIVvphwx1hI_tV2jCgoLIG8HdSepEx_ODSZSaXH60E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);